[theme]
primaryColor = "#ABF617"
backgroundColor = "#131416"
secondaryBackgroundColor = "#1A1B1E"
textColor = "#F4F5F7"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500

[browser]
gatherUsageStats = false
